//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Karpos.Datalayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestComment
    {
        public System.Guid Guid { get; set; }
        public System.Guid RequestGuid { get; set; }
        public string Comment { get; set; }
    
        public virtual Request Request { get; set; }
    }
}
